<?php

include_once( "inc/webpage.php" );


$webpage = new WebPage();
$webpage->head();

?>

<h1>Development</h1>

<div id="content">

<h2>General</h2>

<p>
Bombermaaan is written in C++ and hosted on SourceForge.net. Bombermaaan should run on all 32-bit MS Windows operating systems.
</p>

<p>
See the <a href="contact.php">contact page</a> for a list of the developers of Bombermaaan.
</p>

<h2>Links to SourceForge.net</h2>

<ul>
<li><a href="https://sourceforge.net/projects/bombermaaan/">Project page</a></li>
<li><a href="https://sourceforge.net/project/showfiles.php?group_id=81520">Download section</a></li>
<li><a href="http://bombermaaan.svn.sourceforge.net/viewvc/bombermaaan/">Subversion repository</a></li>
</ul>

<h2>Source code documentation</h2>

The <a href="/doxydoc/html/">source code documentation</a> is generated by <a href="http://www.doxygen.org/">Doxydoc</a>.

<h2>Compile Bombermaaan by yourself</h2>

<p>
There is a (incomplete so far) <a href="http://bombermaaan.svn.sourceforge.net/viewvc/*checkout*/bombermaaan/trunk/docs/how-to-compile.txt?revision=152">how-to guide</a> you can use if you want to compile Bombermaaan by yourself.
Unfortunately, the image and sound files are not in the subversion repository yet. You can get them from the source package, though.
This is true for the small sprites (16 pixels per block). You can delete the RES32 project from your VC++ solution to get Bombermaaan compiled.
The RES32 project generates the DLL for the larger sprites (32 pixels per block).
</p>

<h2>Release steps</h2>

<p>
Compile instructions for Win32
</p>

<ul>
<li>Update version strings in file <code>src/Bombermaaan/Bombermaaan.rc</code> (<a href="http://bombermaaan.svn.sourceforge.net/viewvc/bombermaaan/trunk/src/Bombermaaan/Bombermaaan.rc?r1=529&amp;r2=528&amp;pathrev=529">example</a>)</li>
<li>Update <code>BOMBERMAAAN_VERSION_STRING</code> and <code>BOMBERMAAAN_BUILD_STRING</code> in CGame.cpp (<a href="http://bombermaaan.svn.sourceforge.net/viewvc/bombermaaan/trunk/src/Bombermaaan/CGame.cpp?r1=529&amp;r2=528&amp;pathrev=529">example</a>)</li>
<li>Set line <code>#define ENABLE_DEBUG_KEYS</code> in <code>CGame.cpp</code> to comment</li>
<li>Disable the console window (<code>#define ENABLE_CONSOLE</code> in CGame.cpp)</li>
<li>Select configuration &quot;Release&quot; in the solution</li>
<li>Rebuild the solution</li>
</ul>

<p>
Zip package for Win32
</p>

<ul>
<li>Update the file <code>CHANGELOG.txt</code></li>
<li>Create a new folder <span title="For example, Bombermaaan_1.3_2008-05-07 (stable release) Bombermaaan_rev423_2008-05-07 (experimental release)"><code>Bombermaaan_<i>VERSION</i>_<i>RELEASE-DATE</i></code></span>.</li>
<li>Place the files <code>Bombermaaan.exe</code>, <code>Bombermaaan.dll</code> and <code>FMOD.dll</code> in this directory</li>
<li>Add the readme file <code>Readme.html</code></li>
<li>Add the license file <code>COPYING.txt</code></li>
<li>Add the file <code>CHANGELOG.txt</code></li>
<li>Copy the directory with level files in the new folder</li>
<li>Zip the folder</li>
</ul>

<p>
Installer package for Win32
</p>

<ul>
<li>Update version strings</li>
<li>...</li>
</ul>

<p>
Publishing
</p>

<ul>
<li>Upload the zip file to the SourceForge.net FTP server</li>
<li>Add the file in the file release system</li>
<li>Update download page file web/download.php</li>
<li>Upload file <code>CHANGELOG.txt</code> to web space</li>
</ul>


</div>

<?php

$webpage->tail();

?>
